version: "3.3"
services:

    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./public:/var/www
        networks:
            - php-app-network

    # MySQL database service
    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        volumes:
            - ./public:/var/www
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - php-app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 80:80
        volumes:
            - ./public:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - php-app-network

networks:
    php-app-network:
        driver: bridge

volumes: 
  mysql-data:
